from tkinter import *
from tkinter import font
from tkinter import filedialog
from tkinter import ttk


main=Tk()
main.geometry("1520x850")
main.config(background="navy")
main.title("KS_SUPPORT")
input_frame=Frame(main,bg="white",width="670",height="800")
input_frame.place(x=20,y=20)
output_frame=Frame(main,bg="white",width="670",height="800")
output_frame.place(x=830,y=20)
input_frame_entry1=Entry(input_frame,width="42",bg="white", font=("family","20"))
input_frame_entry1.place(x=20,y=20)
input_frame_entry2=Entry(input_frame,width="42",bg="white", font=("family","20"))
input_frame_entry2.place(x=20,y=70)
input_frame_entry3=Entry(input_frame,width="42",bg="white", font=("family","20"))
input_frame_entry3.place(x=20,y=120)
input_frame_entry4=Entry(input_frame,width="42",bg="white", font=("family","20"))
input_frame_entry4.place(x=20,y=170)
input_frame_entry5=Entry(input_frame,width="42",bg="white", font=("family","20"))
input_frame_entry5.place(x=20,y=220)
input_frame_entry6=Entry(input_frame,width="42",bg="white", font=("family","20"))
input_frame_entry6.place(x=20,y=270)
input_frame_entry7=Entry(input_frame,width="42",bg="white", font=("family","20"))
input_frame_entry7.place(x=20,y=320)
input_frame_entry8=Entry(input_frame,width="42",bg="white", font=("family","20"))
input_frame_entry8.place(x=20,y=370)
input_frame_entry9=Entry(input_frame,width="42",bg="white", font=("family","20"))
input_frame_entry9.place(x=20,y=420)
input_frame_entry10=Entry(input_frame,width="42",bg="white", font=("family","20"))
input_frame_entry10.place(x=20,y=470)
input_frame_entry11=Entry(input_frame,width="42",bg="white", font=("family","20"))
input_frame_entry11.place(x=20,y=520)
input_frame_entry12=Entry(input_frame,width="42",bg="white", font=("family","20"))
input_frame_entry12.place(x=20,y=570)
input_frame_entry13=Entry(input_frame,width="42",bg="white", font=("family","20"))
input_frame_entry13.place(x=20,y=620)
input_frame_entry14=Entry(input_frame,width="42",bg="white", font=("family","20"))
input_frame_entry14.place(x=20,y=670)
input_frame_entry15=Entry(input_frame,width="42",bg="white", font=("family","20"))
input_frame_entry15.place(x=20,y=720)
def output():
    global output_frame
    global input_frame_entry1
    v1=input_frame_entry1.get()
    v1=v1.replace("حماس","7ماس")
    v1=v1.replace("غزه","وزه")
    global input_frame_entry2
    v2=input_frame_entry2.get()
    v2=v2.replace("حماس","7ماس")
    v2=v2.replace("غزه","وزه")
    global input_frame_entry3
    v3=input_frame_entry3.get()
    v3=v3.replace("حماس","7ماس")
    v3=v3.replace("غزه","وزه")
    global input_frame_entry4
    v4=input_frame_entry4.get()
    v4=v4.replace("حماس","7ماس")
    v4=v4.replace("غزه","وزه")
    global input_frame_entry5
    v5=input_frame_entry5.get()
    v5=v5.replace("حماس","7ماس")
    v5=v5.replace("غزه","وزه")
    global input_frame_entry6
    v6=input_frame_entry6.get()
    v6=v6.replace("حماس","7ماس")
    v6=v6.replace("غزه","وزه")
    global input_frame_entry7
    v7=input_frame_entry7.get()
    v7=v7.replace("حماس","7ماس")
    v7=v7.replace("غزه","وزه")
    global input_frame_entry8
    v8=input_frame_entry8.get()
    v8=v8.replace("حماس","7ماس")
    v8=v8.replace("غزه","غ’ز’ة")
    global input_frame_entry9
    v9=input_frame_entry9.get()
    v9=v9.replace("حماس","7ماس")
    v9=v9.replace("غزه","وزه")
    global input_frame_entry10
    v10=input_frame_entry10.get()
    v10=v10.replace("حماس","7ماس")
    v10=v10.replace("غزه","وزه")
    global input_frame_entry11
    v11=input_frame_entry11.get()
    v11=v11.replace("حماس","7ماس")
    v11=v11.replace("غزه","وزه")
    global input_frame_entry12
    v12=input_frame_entry12.get()
    v12=v12.replace("حماس","7ماس")
    v12=v12.replace("غزه","وزه")
    global input_frame_entry13
    v13=input_frame_entry13.get()
    v13=v13.replace("حماس","7ماس")
    v13=v13.replace("غزه","وزه")
    global input_frame_entry14
    v14=input_frame_entry14.get()
    v14=v14.replace("حماس","7ماس")
    v14=v14.replace("غزه","وزه")
    global input_frame_entry15
    v15=input_frame_entry15.get()
    v15=v15.replace("حماس","7ماس")
    v15=v15.replace("غزه","وزه")
    output_frame_label1=Label(output_frame,bg="white",font=("family","20"),fg="black",text=v1)
    output_frame_label1.place(x=20,y=20)
    output_frame_label2=Label(output_frame,bg="white",font=("family","20"),fg="black",text=v2)
    output_frame_label2.place(x=20,y=70)
    output_frame_label3=Label(output_frame,bg="white",font=("family","20"),fg="black",text=v3)
    output_frame_label3.place(x=20,y=120)
    output_frame_label4=Label(output_frame,bg="white",font=("family","20"),fg="black",text=v4)
    output_frame_label4.place(x=20,y=170)
    output_frame_label5=Label(output_frame,bg="white",font=("family","20"),fg="black",text=v5)
    output_frame_label5.place(x=20,y=220)
    output_frame_label6=Label(output_frame,bg="white",font=("family","20"),fg="black",text=v6)
    output_frame_label6.place(x=20,y=270)
    output_frame_label7=Label(output_frame,bg="white",font=("family","20"),fg="black",text=v7)
    output_frame_label7.place(x=20,y=320)
    output_frame_label8=Label(output_frame,bg="white",font=("family","20"),fg="black",text=v8)
    output_frame_label8.place(x=20,y=370)
    output_frame_label9=Label(output_frame,bg="white",font=("family","20"),fg="black",text=v9)
    output_frame_label9.place(x=20,y=420)
    output_frame_label10=Label(output_frame,bg="white",font=("family","20"),fg="black",text=v10)
    output_frame_label10.place(x=20,y=470)
    output_frame_label11=Label(output_frame,bg="white",font=("family","20"),fg="black",text=v11)
    output_frame_label11.place(x=20,y=520)
    output_frame_label12=Label(output_frame,bg="white",font=("family","20"),fg="black",text=v12)
    output_frame_label12.place(x=20,y=570)
    output_frame_label13=Label(output_frame,bg="white",font=("family","20"),fg="black",text=v13)
    output_frame_label13.place(x=20,y=620)
    output_frame_label14=Label(output_frame,bg="white",font=("family","20"),fg="black",text=v14)
    output_frame_label14.place(x=20,y=670)
    output_frame_label15=Label(output_frame,bg="white",font=("family","20"),fg="black",text=v15)
    output_frame_label15.place(x=20,y=720)
def clear():
    global output_frame
    global input_frame_entry
    output_frame=Frame(main,bg="white",width="670",height="800")
    output_frame.place(x=830,y=20)
button=Button(main,text="ulter",font=("family","15"),relief="flat",command=output)
button.place(x=735,y=260)
button=Button(main,text="clear",font=("family","15"),relief="flat",command=clear)
button.place(x=730,y=500)
main.mainloop()
